### ISSUE TITLE
Ao ser iniciado o jogo já existe um resultado exibido na tela

### ISSUE THREAD

**Issue by henriquecrang** [Skynii/pedra#1]
Após o usuário entrar com seu nome, ele já é apresentado com o resultado de uma partida antes mesmo de ter jogado. No caso "Papel cobre Pedra. Você Ganha!".

Esse elemento deveria nascer oculto e somente ser exibido após a primeira partida ser disputada.

**Comment by Skynii** [comment]
Obrigada Henrique.

Já ajustei isso. ;)
